
DROP TABLE IF EXISTS `SVC_MTTO_NIVEL`;
CREATE TABLE `SVC_MTTO_NIVEL` (
  `ID_MTTONIVEL` int(11) NOT NULL AUTO_INCREMENT,
  `DES_NIVEL` varchar(45) DEFAULT NULL,
  `IND_ACTIVO` bit(1) DEFAULT NULL,
  `ID_USUARIO_ALTA` int(5) DEFAULT NULL,
  `FEC_ALTA` datetime DEFAULT current_timestamp(),
  `ID_USUARIO_BAJA` int(5) DEFAULT NULL,
  `FEC_BAJA` datetime DEFAULT NULL,
  `ID_USUARIO_MODIFICA` int(5) DEFAULT NULL,
  `FEC_ACTUALIZACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_MTTONIVEL`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
